### ISSUE TITLE
flask init exception when providing a folder path

### ISSUE THREAD

**Issue by cris-m** [nickjj/flask-db#13]
I was avoiding to create `alembic.ini` file and `db` folder on the route directory. when providing the path in `flask db init ./location/migrations` command I get an exception. Here is the exception traceback:
```
Traceback (most recent call last):
  File "/home/python/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/python/.local/lib/python3.10/site-packages/flask/cli.py", line 985, in main
    cli.main()
  File "/home/python/.local/lib/python3.10/site-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/home/python/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/python/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/python/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/python/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/python/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/python/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/python/.local/lib/python3.10/site-packages/flask/cli.py", line 427, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/python/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/python/.local/lib/python3.10/site-packages/flask_db/cli.py", line 31, in init
    copied_files, existing_files = generate_configs(path,
  File "/home/python/.local/lib/python3.10/site-packages/flask_db/init.py", line 80, in generate_configs
    os.path.join(alembic_ini_dst_path(path), "alembic.ini"))
  File "/home/python/.local/lib/python3.10/site-packages/flask_db/init.py", line 61, in alembic_ini_dst_path
    return pathlib.Path(path).parents[file_depth_count(path)]
  File "/usr/local/lib/python3.10/pathlib.py", line 530, in __getitem__
    raise IndexError(idx)
IndexError: 3
```
The `db` folder was created but `alembic.ini` file was not get created.

**Comment by nickjj** [comment]
Can you show me your project's exact directory structure and the exact command you ran?

**Comment by cris-m** [comment]
Here is my structure folder:
```
.
├── app
│   ├── api
│   ├── cli
│   ├── config
│   ├── files
│   ├── lib
│   ├── models
│   └── tests
├── bin
├── client
│   ├── node_modules
│   ├── public
│   ├── src
│   └── tests
├── db
│   └── versions
├── mask_rcnn
│   ├── config
│   ├── lib
│   ├── mrcnn
└── nginx
    ├── cache
    ├── config
    └── logs
```
The `db` folder inside root folder. I wanted to put it in `app/migrations` folder.

**Comment by nickjj** [comment]
What was the exact command you ran?

You originally posted you ran `flask db init ./location/migrations` but you don't have a `location` directory there.

**Comment by cris-m** [comment]
> What was the exact command you ran?
> 
> You originally posted you ran `flask db init ./location/migrations` but you don't have a `location` directory there.

It was just an example. The command I executed was `flask db init ./app/migrations`

**Comment by nickjj** [comment]
I'm not able to reproduce this.

I deleted my `alembic.ini` file and `db/` directory then ran: `flask db init hello/migrations` and it created an `alembic.ini` file configured to use `hello/migrations` and also created that directory. I used https://github.com/nickjj/docker-flask-example as an example project.

Also there's tests set up in this repo to use a custom directory with end to end tests to make sure everything works:

https://github.com/nickjj/flask-db/blob/109199f8c4a01e923afd1fe6fac34624e48c4544/.github/workflows/ci.yml#L40-L58

**Comment by cris-m** [comment]
Okay for now I will close the issue. I will look again on my project configuration

**Comment by nickjj** [comment]
I don't think Python would do anything differently with the `./` you've been prefixing to your paths but that is one difference between your commands and mine. It wouldn't hurt for you to try it without that even though technically it shouldn't make a difference.
